name: 'Run E2E template tests'
inputs:
  stack-name:
    description: 'Name of ZenML stack to build (see `tests/conftest.py:configure_stack()`)'
    required: true
runs:
  using: "composite"
  steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Concatenate requirements
      shell: bash
      run: |
        cat requirements.txt test-requirements.txt template/requirements.txt >> all-requirements.txt

    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv
      with:
        requirement_files: all-requirements.txt

    - uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      with:
        requirement_files: all-requirements.txt
        
    - name: Install requirements
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      shell: bash
      run: |
        pip install -r all-requirements.txt
    
    - name: Install integrations
      shell: bash
      run: |
        zenml integration install sklearn mlflow s3 kubernetes kubeflow slack evidently -y

    # e2e example was not released yet, so relies on some recent develop changes
    # TODO: remove after #1715, #1711, #1707 and #1703 are released
    - name: Install develop ZenML
      shell: bash
      run: |
        pip install --upgrade git+https://github.com/zenml-io/zenml.git@develop

    - name: Run pytests
      shell: bash
      env:
        ZENML_STACK_NAME: ${{ inputs.stack-name }}
      run: |
        pytest tests
