name: 'Run E2E template tests'
inputs:
  stack-name:
    description: 'Name of ZenML stack to build (see `tests/conftest.py:configure_stack()`)'
    required: true
  os:
    description: 'Operating system to run tests on'
    required: true
  ref_zenml:
    description: 'Ref of ZenML package'
    required: false
    default: ''
  ref_template:
    description: 'Ref of this tempalte repo'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      with:
        repository: zenml-io/template-e2e-batch
        ref: ${{ inputs.ref_template }}
        path: ./local_checkout

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Configure git (non-Windows)
      if: ${{ inputs.os != 'windows-latest' }}
      shell: bash
      run: |
        git config --global user.email "info@zenml.io"
        git config --global user.name "ZenML GmbH"
    
    - name: Configure git (Windows)
      if: ${{ inputs.os == 'windows-latest' }}
      shell: bash
      run: |
        "C:\Program Files\Git\bin\git.exe" config --global user.email "info@zenml.io"
        "C:\Program Files\Git\bin\git.exe" config --global user.name "ZenML GmbH"

    - name: Install ZenML and wheel
      if: ${{ inputs.ref_zenml != '' }}
      shell: bash
      run: |
        pip install --force --upgrade git+https://github.com/zenml-io/zenml.git@${{ inputs.ref_zenml }} wheel
    
    - name: Install ZenML and wheel
      if: ${{ inputs.ref_zenml == '' }}
      shell: bash
      run: |
        pip install --force --upgrade zenml wheel
    
    - name: Concatenate requirements
      shell: bash
      run: |
        zenml integration export-requirements -o ./local_checkout/integration-requirements.txt sklearn mlflow s3 kubernetes kubeflow slack evidently
        cat ./local_checkout/requirements.txt ./local_checkout/test-requirements.txt ./local_checkout/template/requirements.txt ./local_checkout/integration-requirements.txt >> ./local_checkout/all-requirements.txt

    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv
      with:
        requirement_files: ./local_checkout/all-requirements.txt

    - uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      with:
        requirement_files: ./local_checkout/all-requirements.txt
        
    - name: Install requirements
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      shell: bash
      run: |
        pip install -r ./local_checkout/all-requirements.txt
    
    - name: Reinstall ZenML after requirements
      if: ${{ inputs.ref_zenml != '' }}
      shell: bash
      run: |
        pip install --force --upgrade git+https://github.com/zenml-io/zenml.git@${{ inputs.ref_zenml }}

    - name: Run pytests
      shell: bash
      env:
        ZENML_STACK_NAME: ${{ inputs.stack-name }}
      run: |
        pytest ./local_checkout/tests
